CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY,
  name TEXT NOT NULL
); CREATE TABLE IF NOT EXISTS events (
  id INTEGER PRIMARY KEY,
  name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS event_users (
  eventId INTEGER NOT NULL,
  userId INTEGER NOT NULL,

  FOREIGN KEY (eventId) REFERENCES events (id)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
  FOREIGN KEY (userId) REFERENCES users (id)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
  UNIQUE(eventId, userId)
);
